version: "3.9"
services:
  postgres:
    build: ./db
    container_name: hs-wieght-db
    environment:
      POSTGRES_DB: weight
      POSTGRES_USER: weight
      POSTGRES_PASSWORD: weight
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - 5050:80
    restart: unless-stopped
    logging:
      driver: none
